// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnxclsslqgonczgtiwav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueGNsc3NscWdvbmN6Z3Rpd2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjc1MDksImV4cCI6MjA2MDkwMzUwOX0.AF2JNk8B1pYeA7hYjm-ZLCGbq0W4iOQXxv93x1LTmFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true, // Changed to true to enable session persistence
    detectSessionInUrl: true,
    storageKey: 'glm-auth-token',
    flowType: 'pkce',
  },
});

// Log Supabase initialization for debugging
console.log('Supabase client initialized with URL:', SUPABASE_URL);